### ISSUE TITLE
Air quality entity is deprecated, migrate to sensors

### ISSUE THREAD

**Issue by p0wertiger** [iprak/weatherapi#13]
With version v0.6 air quality entity has been introduced. According to [documentation located here](https://developers.home-assistant.io/docs/core/entity/air-quality), air quality entity is deprecated. I found this issue when I had to make my own templates to pull out attributes from the entity as their own sensors, that's because you can't display entity attributes in Lovelace. The correct way explained is to implement measurements as separate sensors.

**Comment by iprak** [comment]
Bummer .. I was referencing the [AirQuality](https://github.com/home-assistant/core/blob/dev/homeassistant/components/air_quality/__init__.py) class itself and it gave no hint of such deprecation.
