### ISSUE TITLE
Pressure is always returned as "0"

### ISSUE THREAD

**Issue by MikeKade** [iprak/weatherapi#15]
I have setup several lat / lon for various places that I want to measure. I am using the free service at the moment in order to determine if this service will give me what I need in regards to the weather. 

Currently, both of the locations that I have selected will only return "0" for the pressure instead of inches of mercury (imperial measurements).

**Comment by iprak** [comment]
Thanks for reporting that, incorrect data pieces were being extracted. While evaluating the data, I also noted that [weatherAPI documentation](https://www.weatherapi.com/docs/) or the data is incorrect. 

The pressure is reported as pressure_mb (Pressure in millibars) and pressure_in (Pressure in inches). But actually the values are in Pa and Psi.
