### ISSUE TITLE
Forecast Option

### ISSUE THREAD

**Issue by hw-monkey** [iprak/weatherapi#17]
Given that this provides UV Index for history, I was hoping it would include it for forecast info. I see the API support UV. How could one display forecasted UV data in Home Assistant using this integration?

**Comment by iprak** [comment]
The [Forecast entity](https://developers.home-assistant.io/docs/core/entity/weather/) does not support UV value. As such I cannot pass UV data in any standard format. I did not find UV data being displayed in any standard Forecast cards, not sure if there any custom cards which can do so.
