### ISSUE TITLE
Hourly forecast is not updating

### ISSUE THREAD

**Issue by ianpra** [iprak/weatherapi#24]
Hi,

When configured to generate an hourly forecast it is always starting at midnight, regardless of what time of day it is, and doesn't appear to be updating it during the day.

This screenshot was taken at 11:35 am, and you will see that the first hourly forecast entry is at midnight for today...

![2023-01-08 11_35_28-Window](https://user-images.githubusercontent.com/25880217/211194283-208aa654-2270-43d9-8a2c-fab08e023d46.png)

Kind regards

Ian

**Comment by iprak** [comment]
Your observation is correct. WeatherAPI always returns the daily forecast split into hours starting from midnight. There is optional parameter to control this behavior, which might have the data size. I will look into skipping past data based on current hour.

**Comment by ianpra** [comment]
Hi,

I think I've solved my issue - I'm looking to use the hourly forecast data with this Lovelace card - `https://github.com/decompil3d/lovelace-hourly-weather`, and I've just realised that I can use an offset (which will accept a template) so the card only starts displaying from the current hour. Up to now it has just been dispalying the forecast from midnight to 6am, as that is the first 6 hourly values returned.

I am curious as to what data is returned for hours which have past - eg when you query the API at 10am, what values are returned for the hours from midnight to 9am - do they leave it as what they forecast it to be, or do they update it with the actual data (which is now effectively historical data) - as technically you can't forecast something that has already happened!

I'm going to save the sensor values and and compare again later in the day to see if they change once the forecast period has passed.

Kind regards

Ian

**Comment by ianpra** [comment]
Hi @iprak 

Just updated to the latest release, and this all works now without having to apply an offset in the card.

Thanks for your help and the quick fix.

Kind regards

Ian
