### ISSUE TITLE
HAOS warning

### ISSUE THREAD

**Issue by Deewee007** [iprak/weatherapi#33]
Hi there,

Recieved the folowing error after the latest upgrade.

The integration weatherapi is using the deprecated forecast attribute.
Please report it to the custom integration author.

![image](https://github.com/iprak/weatherapi/assets/77449877/9a84fc16-b2fd-4217-93b5-2e00da9bc5d1)

**Comment by cihanulusoy** [comment]
I’m receiving the same warning. HA 2023.9.0, Supervisor 2023.08.3, OS 10.5, WeatherAPI integration v1.1.0

**Comment by iprak** [comment]
This requirement is new as of 2023.9.0. You should not see any functional shortcoming till 2024.3.0 .. I will take a look at it sometime.
