### ISSUE TITLE
different of weather between weatherapi and météofrance 

### ISSUE THREAD

**Issue by defaliz** [iprak/weatherapi#38]
Hi,
thanks for the work !
i've two weather integrations, and with weatherapi the weather today in Normandy is rainy ! (with meteo france integration weather is sunny, and it's the real weather today)

when i use weatherapi with curl api, the information is good, but not with HA ?
may be there is a problem with latitude and longitude, but i don't know how change it...
regards

**Comment by defaliz** [comment]
thanks for reply...
the datas are : Lat/Lon:	49.9, 1.27
but since my post, now the text is "sunny" like for meteo france...
i think it was some problem with updating, now all is OK ! (you can closed my post)
sorry for disturbing...
regards

**Comment by iprak** [comment]
I think it might be worth considering if the weather state should be cleared if the data fetch failed. I have seen data fetch fail occasionally and then it corrects itself. Showing the last good state doesn't feel correct.

**Comment by iprak** [comment]
The last 2 release are tackling JSON decoding better and log if the response received was incorrect. This should help with mismatches.

**Comment by defaliz** [comment]
thank for update iprak
